name: Envió de Correo Diario

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta a las 13:00 UTC (8:00 AM hora de Colombia) de lunes a sábado
    - cron: '36 16 * * 1-6'

jobs:
  enviar-correo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Instalar dependencias del correo
        run: pip install supabase pandas

      - name: Ejecutar el script del correo
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python enviar_correo.py
