name: Envió de Correo Diario

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta a las 13:00 UTC (8:00 AM hora de Colombia/CDMX, por ejemplo)
    # De lunes (1) a sábado (6)
    - cron: '0 13* * 1-6'

jobs:
  enviar-correo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar el script del correo
        run: python app.py
